site_name: My Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand

nav:
  - Home: index.md
  - About: about.md
  - vpc: vpc-cloud.md
